config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shifts do
  	member do
  		post 'clock_in'
  		post 'clock_out'
  	end
    resources :clock_events, only: [:destroy, :edit, :update]
  end


  # Root path
  root to: 'shifts#index'

  # Routes for missing path
  match '/*path', via: :all, to: 'application#missing_path'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_event.rb
class ClockEvent < ApplicationRecord
	# Associations
	belongs_to :shift

	# Validations
	validates :clock_in, presence: true, if: Proc.new{|obj| !obj.new_record?  }
	validates :clock_out, presence: true, if: Proc.new{|obj| !obj.new_record? }
	validate  :check_clock_out_time

	def check_clock_out_time
		if clock_out && clock_out < clock_in
			errors.add(:clock_out, "time should not be less than clockin time.")
		end
		if !self.new_record? and self.clock_in and self.clock_out
			if ClockEvent.where(shift_id: self.shift_id, clock_in: self.clock_in..self.clock_out, clock_out: self.clock_in..self.clock_out).any?
				errors.add(:clock_event, "Conflict with your existing clock events.")
			end
		end
	end

	def get_total_time
    Time.at(self.clock_out - self.clock_in).utc.strftime "%H:%M:%S"
	end

end

app/models/shift.rb
class Shift < ApplicationRecord
	# Associations
	has_many :clock_events, dependent: :destroy
	belongs_to :user

	# Validations
	validates :shift_date, presence:true, inclusion: { in: (Date.today..Date.today), message: 'Can not create future or past shift' }
	validates :title, presence:true, length: { maximum: 255 }
	validates_uniqueness_of :shift_date, scope: :user_id, message: 'You have already created a shift on this day.'

	# This method is created to get the status of clock event
	def get_clock_out_event
		clock_events.where(clock_out: nil).last
	end

	def is_clock_in?
		is_clock_in = false
		if clock_events.blank? || !get_clock_out_event
			is_clock_in = true
		end
		is_clock_in
	end

	def get_last_clock_in_time
		clock_events.last.clock_in.strftime("%H:%M:%S on %d/%m/%Y")
	end

	def get_last_clock_out_time
		clock_events.last.clock_out.strftime("%H:%M:%S on %d/%m/%Y")
	end

	# Get total time of shift
	def total_time_spent
		total_time = 0
		clock_events.each do |clock_event|
		  if clock_event.clock_out
		    time_difference = clock_event.clock_out - clock_event.clock_in
		    total_time += time_difference
		  end
		end
		Time.at(total_time).utc.strftime "%H:%M:%S"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Virtual attribute for authentication via username or email
  attr_accessor :login

  PASSWORD_COMPLEXITY = /\A(?=.*?[A-Z])(?=.*?[a-z])((?=.*?[0-9])|(?=.*?[#?!@$%^&*-])).{8,}/x

  # Devise configuration
  devise :database_authenticatable, :registerable

  # Associations
  has_many :shifts, dependent: :destroy
  has_many :clock_events, through: :shifts

  # Validations
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :name, presence: true, length: { minimum: 2, maximum: 255 }
  validates :username, presence: :true
	validates :password,
    format: { with: PASSWORD_COMPLEXITY, message: 'needs to be complex!' },
    on: :create

  # Overwriting devise's method
  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def missing_path
		redirect_to(
			root_path,
			alert: 'Path that you were looking does not belong to us!'
		)
	end

	protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit :sign_up, keys: [:name, :username, :email, :password, :password_confirmation]
		devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password, :password_confirmation]
  end
end

app/controllers/clock_events_controller.rb
class ClockEventsController < ApplicationController
	before_action :set_shift
	before_action :set_clock_event

	def edit
		respond_to do |format|
			format.js
		end
	end

	def update
		if @clock_event.update_attributes(clock_event_params)
			flash[:notice] = "Clock event has been updated"
		else
			flash[:alert] = @clock_event.errors.full_messages.join(", ")
		end
		redirect_to shift_path(@shift)
	end

	def destroy
		@clock_event.destroy
		flash[:notice] = "Clock event has been destroyed."
		redirect_to shift_path(@shift)
	end

	private

	def set_shift
		@shift = current_user.shifts.find_by(id: params[:shift_id])
		missing_path if @shift.blank?
	end

	def set_clock_event
		@clock_event = @shift.clock_events.find_by(id: params[:id])
		missing_path if @clock_event.blank?
	end

	def clock_event_params
		params.require(:clock_event).permit(:clock_in, :clock_out)
	end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
	before_action :set_shift, except: [:index, :new, :create]

	def index
		@shifts = current_user.shifts
	end

	def show
		# @clock_events = @shift.clock_events
		# unless @clock_events.blank?
		# 	@clock_event_status = @shift.get_clock_out_event
		# 	# To display last clock out time
		# 	@last_clock_out = @clock_events.last.clock_out if @clock_event_status.blank?
		# end
		# @clock_out =@shift.clock_events.where(clock_out: nil)

	end

	def new
		@shift = current_user.shifts.new
	end

	def edit; end

	def create
		@shift = current_user.shifts.new(shift_params)
		if @shift.save
			flash[:notice] = "Your shift is created"
			redirect_to shifts_path
		else
			flash[:alert] = @shift.errors.full_messages.join(",")
			render 'new'
		end
	end

	def update
		if @shift.update_attributes(shift_params)
			flash[:notice] = "Your shift has been updated"
			redirect_to shifts_path
		else
			flash[:alert] = @shift.errors.full_messages.join(",")
			render 'edit'
		end
	end

	def destroy
		@shift.destroy
		flash[:notice] = "Your shift has been destroyed!"
		redirect_to shifts_path
	end

	def clock_in
		@clock_event = ClockEvent.new(shift: @shift, clock_in: Time.now)
		if @clock_event.save
			flash[:notice] = "You clocked in at #{@clock_event.clock_in.strftime("%H:%M:%S on %d/%m/%Y")}"
			redirect_to shifts_path
		else
			puts @clock_event.errors.full_messages
			flash[:alert] = "Please, clock out first!"
			render 'shifts/show'
		end
	end

	def clock_out
		# Search the clock event where clock_out is nil
		if @shift.get_clock_out_event&.update(clock_out: Time.now)
			flash[:notice] = "You have clocked out of the system at #{@shift.get_last_clock_out_time}"
			redirect_to shifts_path
		else
			flash[:alert] = "Please, clock in first!"
			render 'shifts/show'
		end
	end

	private

	def set_shift
		@shift = current_user.shifts.find_by(id: params[:id])
		missing_path if @shift.blank?
	end

	def shift_params
		params.require(:shift).permit(:shift_date, :title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
		content_for(:header) { text.to_s }
	end

	def formatted_date(date)
		if date
			return date.strftime("%d/%m/%Y")
		end
	end

	def formatted_datetime(datetime)
		if datetime
			return datetime.strftime("%H:%M:%S %d/%m/%Y")
		end
	end
end

app/helpers/clock_events_helper.rb
module ClockEventsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/clock_events/_clock_events.html.erb
<% @shift.clock_events.each do |clock_event| %>
  <div class="well">
    <p>Clock in: <%= clock_event.clock_in.strftime("%H:%M:%S on %d/%m/%Y") %></p>
    <% if clock_event.clock_out.present? %>
      <p>Clock out: <%= clock_event.clock_out.strftime("%H:%M:%S on %d/%m/%Y") %></p>
      <p>Total time: <%= clock_event.get_total_time %></p>
    <% end %>
    <button type="button" class="label label-default edit_event" shift-id= "<%= @shift.id %>" data-id="<%= clock_event.id %>">Edit </button>
    <%= link_to 'Delete', shift_clock_event_path(@shift, clock_event), method: :delete, data: { confirm: "Are you sure?" }, class: 'label label-danger' %>
  </div>
<% end %>

app/views/clock_events/_form.html.erb
<%= form_for ([shift, clock_event]) do |f| %>
	<div class="row">
		<div class='col-sm-9'>
		  <div class="form-group">
		  	<div class='input-group date datetimepicker'>
		    	<%= f.text_field :clock_in, label: false, placeholder: "Select clock in time", class: "form-control", value: clock_event.clock_in.strftime("%H:%M:%S") %>
		     	<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		    </div>
		    <br>
		    <div class='input-group date datetimepicker' >
		    	<%= f.text_field :clock_out, label: false, placeholder: "Select clock out time", class: "form-control", value: clock_event.clock_out&.strftime("%H:%M:%S") %>
		     	<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		    </div>
		    <br>
		    <%= f.submit "Update Event", class: 'btn btn-primary' %>
		  </div>
		</div>
	</div>
<% end %>


	<script>
		let current = moment()
		$('.datetimepicker').datetimepicker({
	   sideBySide: true,
	   format: "h:mm A"
	  });
	</script>

app/views/clock_events/_show_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="clock_event" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Clock Event</h4>
      </div>
      <div class="modal-body" id="clock_event_form"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/clock_events/edit.js.erb
$('#clock_event_form').html("<%= escape_javascript(raw( render partial: 'clock_events/form', locals: { shift: @shift, clock_event: @clock_event }))%>")
$('#clock_event').modal('show'); 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Clockify", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<% if user_signed_in? %>
	      <li><a href="#"><span class="glyphicon glyphicon-user"></span> <%= current_user.try(:name) %> </a></li>
	      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
	    <% else %>
        <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
        <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-user"></span> Log In </a></li>
	    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clockify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<body>
		<div class="container">
			<% flash.each do |key,value| %>
				<div class="alert alert-<%= key %>">
	        <%= value %>
				</div>
			<% end %>
		</div>
		<%= render 'layouts/header' %>
		<div class="container">
			<h1><%= yield :header %></h1>
		  <%= yield %>
		</div>
		<%= yield :javascript %>
	</body>
</html>

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
	<div class="row">
		<div class='col-sm-6'>
		  <div class="form-group">
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		  	<div class='input-group date' id='shift_date'>
		    	<%= f.text_field :shift_date, label: false, placeholder: "Select the date", class: "form-control" %>
		     	<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		    </div>
		    <br>
		    <%= f.submit "#{@shift.new_record? ? 'Save' : 'Update'} Shift", class: 'btn btn-primary' %>
		  </div>
		</div>
	</div>
<% end %>

<% content_for :javascript do %>
	<script>
		$('#shift_date').datetimepicker({
	   sideBySide: true,
	   format: "YYYY-MM-DD"
	  });
	</script>
<% end %>

app/views/shifts/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Shift</h1>
    <h5><span class="label label-danger">Update the information of a shift </span></h5>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <%= link_to 'Back', root_path, class: 'label label-primary' %>
</div>

app/views/shifts/index.html.erb
<div class="container">
  <div class="page-header">
    <h2>Shifts</h2>
    <h4><span class="label label-primary"> Create shifts or get the details of existing ones. </span></h4>
    <%= link_to 'Create Shift', new_shift_path, class: 'btn btn-sm btn-default' %>
  </div>
</div>
<div class="container">
	<% if @shifts.exists? %>
	  <table class="table table-striped">
	    <thead>
	      <tr>
	        <th class="text-center">Title</th>
	        <th class="text-center">Date</th>
	        <th class="text-center">Total Time Spent on Shift</th>
	        <th class="text-center">Clock In/Clock Out</th>
	        <th class="text-center">Actions</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @shifts.each do |shift| %>
	        <tr>
	          <td class="text-center"><%= shift.title %></td>
	          <td class="text-center"><%= formatted_date(shift.shift_date) %></td>
	          <td class="text-center"><%= shift.total_time_spent %></td>
	          <td class="text-center">
	          	<% if shift.is_clock_in? %>
            		<%= link_to 'Clock In', clock_in_shift_path(shift), method: 'POST', class: 'label label-info' %>
            	<% else %>
        				<%= link_to 'Clock Out', clock_out_shift_path(shift), method: 'POST', class: 'label label-danger' %>
        			<% end %>
	          </td>
	          <td class="text-center">
	          	<%= link_to "Show", shift_path(shift), class: 'label label-info'%>
            	<%= link_to "Edit", edit_shift_path(shift), class: 'label label-primary'%>
            	<%= link_to "Delete", shift_path(shift), method: :delete, data: { confirm: "Are you sure?" }, class: 'label label-danger' %>
	          </td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	<% else %>
		<h3 class="well">There are no shifts of you yet. Create one!</h3>
	<% end %>
</div>

app/views/shifts/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Create Shift</h1>
    <h4><span class="label label-danger">Fill in the information to create your shift </span></h4>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
  <%= link_to 'Back', root_path, class: 'btn btn-default' %>
</div>

app/views/shifts/show.html.erb
<div class="container">
  <div class="well">
    <h3>Shift Details <%= link_to 'Back', root_path, class: 'btn btn-default btn-sm' %></h3>
    <p>
      Find your shift details and clock in/clock out.
    </p>
    <h4>
      <span class="label label-primary"> Current time: <%= Time.zone.now.strftime("%H:%M:%S") %> Date: <%= Time.zone.now.strftime("%e %B %Y") %></span>
    </h4>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <p>Shift Date: <%= formatted_date(@shift.shift_date) %></p>
      <% if @shift.is_clock_in? %>
        <% if @shift.clock_events.any? %>
          <p>You clocked out at <%= @shift.get_last_clock_out_time %> Please clock in!</p>
        <% end %>
        <%= link_to 'Clock In', clock_in_shift_path(@shift), method: 'POST', class: 'btn btn-primary btn-md' %>
      <% else %>
        <p><b>You clocked in at <%= @shift.get_last_clock_in_time %> Please clock out.</b></p>
        <%= link_to 'Clock Out', clock_out_shift_path(@shift), method: 'POST', class: 'btn btn-danger btn-md' %>
      <% end %>
    </div>
    <div class="well">
      <h3><b>Logs of clock events</b></h3>
      <%= render 'clock_events/clock_events' %>
    </div>
    <%= render 'clock_events/show_modal' %>
    <div class="panel-footer"><u>Clock event logs of <%= current_user.name %></u> </div>
  </div>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $('.edit_event').click(function() {
      let clock_event_id = $(this).attr('data-id')
      let shift_id = $(this).attr('shift-id')
      if(clock_event_id && shift_id){
        let url = "/shifts/"+shift_id+"/clock_events/"+clock_event_id+"/edit"
        $.ajax({url: url})
      }
    });
  </script>
<% end %>